### ISSUE TITLE
Running with syntax extensions

### ISSUE THREAD

**Issue by colegleason** [rleonid/BisectFromOasis#1]
Hi, how would I run this is I need the pre-processor to compile with syntax extensions?

```
$ ocaml setup.ml -build

Finished, 0 targets (0 cached) in 00:00:00.
Configuration "true: quiet, debug, tests", line 1, characters 20-25:
Warning: the tag "tests" is not used in any flag or dependency declaration, so it will have no effect; it may be a typo. Otherwise you can use `mark_tag_used` in your myocamlbuild.ml to disable this warning.
+ /Users/cole/.opam/4.02.2/bin/ocamlfind ocamldep -package camlprime -package core -syntax camlp4o -package sexplib.syntax -package threads -pp 'camlp4o str.cma /Users/cole/.opam/4.02.2/lib/bisect/bisect_pp.cmo' -modules polynomial/polynomial.ml > polynomial/polynomial.ml.depends
Warning: -pp overrides the effect of -syntax partly
File "polynomial/polynomial.ml", line 60, characters 30-31:
Parse error: "end" expected after [str_items] (in [module_expr])
File "polynomial/polynomial.ml", line 1:
Error: Error while running external preprocessor
Command line: camlp4o str.cma /Users/cole/.opam/4.02.2/lib/bisect/bisect_pp.cmo 'polynomial/polynomial.ml' > /var/folders/0s/ll1dx5850r577h5tlf6skk8h0000gn/T/ocamlpp14b7e0

Command exited with code 2.
Compilation unsuccessful after building 26 targets (22 cached) in 00:00:00.
```

**Comment by rleonid** [comment]
I don't know, what are you trying to do exactly? Can you point me to a fork of this project or one of yours?

This project was more of a basic attempt to get the `OCaml` tool chain to do something very specific. The solution is far from perfect or ideal, and clearly exposes the encumbrances of working with these tools. Consequently, I don't use `bisect` anymore (easier with `bisect_ppx`) and also try to avoid `Oasis` as well. Let me know how I can help.

**Comment by colegleason** [comment]
I just have the `sexplib.syntax` extension, in order to have `module X with sexp` syntax. I actually didn't know of `bisect_ppx` and just tried that and was able to get it working. Thanks for introducing that to me!

**Comment by rleonid** [comment]
No worries, glad it worked out.
